# Generated by Django 6.1 on 2026-08-24 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("paginas", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Progresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pretendo_ler", "Pretendo ler"),
                            ("lendo", "Lendo"),
                            ("pausado", "Pausado"),
                            ("concluido", "Concluído"),
                        ],
                        default="pretendo_ler",
                        max_length=20,
                    ),
                ),
                ("pagina_atual", models.PositiveIntegerField(default=0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to="biblioteca.livro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("inicio", "Início"),
                            ("avanco", "Avanço"),
                            ("pausa", "Pausa"),
                            ("conclusao", "Conclusão"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pagina", models.PositiveIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="biblioteca.livro",
                    ),
                ),
                (
                    "progresso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="biblioteca.progresso",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="progresso",
            constraint=models.UniqueConstraint(
                fields=("usuario", "livro"), name="progresso_unico_por_usuario_livro"
            ),
        ),
    ]
